import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "remixicon/fonts/remixicon.css";
import RecoilRootProvider from "@/state/RecoilRootProvider";
import SocketProvider from "@/state/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RecoilRootProvider>
        <body className={inter.className}>
          <SocketProvider>
            <main className="main">{children}</main>
          </SocketProvider>
        </body>
      </RecoilRootProvider>
    </html>
  );
}
